# https://chatgpt.com/c/67e52d1f-fd1c-8004-9693-e4c3cc115836

name: Shift-To-QA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #   image: my-local-image:latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Prepare version and tag
        run: |
          git config --global --add safe.directory /home/ahmetsoner/AS/prs/pars

          CHANNEL=alpha

          BASE_VERSION=$(vereasy phase qa $CHANNEL --next-release --print=base)
          echo "Version retrieved: $BASE_VERSION"

          git checkout -b release/$BASE_VERSION-$CHANNEL dev

          BUILD_VERSION=$(vereasy phase qa $CHANNEL --next)

          git tag -a $BUILD_VERSION -m "$CHANNEL release $BUILD_VERSION"

          git checkout dev

          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
